cricket_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 1

